### ISSUE TITLE
Potion Use Vibration sets vibration to 100%

### ISSUE THREAD

**Issue by Renpona** [notasuka/Viberaria#5]
When I turn on Potion Use Vibration, it seems to set the vibration level to 100% constantly, regardless of what else is happening in the game and what other settings are enabled, and hold it there for the entire time that Potion Use Vibration is turned on. It does not respond to potions or any other ingame events. The vibration level will only drop below 100% when either Potion Use Vibration or Viberaria itself are turned off.

The specific behavior:

If only Potion Use Vibration is turned on, with no other modes active, then Viberaria will send one request to set vibration to 100%, and then not adjust the vibration any more until it or Viberaria are turned off.

If both Potion Use Vibration and Health Vibration Scaling are turned on, then Viberaria will rapidly (as fast as possible, with no speed limiting) and continuously toggle the vibration level back and forth between 100% and whatever value the health vibration would normally cause.

Game environment:
Viberaria 2.9, with no other mods
tModLoader v2024.3.3.2
Terraria v1.4.4.9

**Comment by MysticMia** [comment]
This is likely caused by the implementation of PotionVibration. It gets called by GetHealLife or GetHealMana from ModPlayer (see [tModLoader.net/ModPlayer/GetHealLife](https://docs.tmodloader.net/docs/stable/class_mod_player.html#aea058be17af7e3152a456a5951fae5c6)) but upon testing I found that this function gets called every tick if the player has any health or mana potion in their inventory.

A fix would be to use GlobalItem.OnConsumeItem instead:
```cs
public class tGlobalItem : GlobalItem
{
    public override void OnConsumeItem(Item item, Player player)
    {
        if (item.type == ItemID.HealingPotion ||
            item.type == ItemID.GreaterHealingPotion ||
            item.type == ItemID.SuperHealingPotion ||
            item.type == ItemID.ManaPotion ||
            item.type == ItemID.GreaterManaPotion ||
            item.type == ItemID.SuperManaPotion)
        {
            if (player == Main.LocalPlayer)
                PotionVibration(item);
        }
    }
}
```

I looked at some other functions but couldn't get them to work. This one seems to work though.
