### ISSUE TITLE
Damage Vibration and Effect Damage Vibration don't seem to work

### ISSUE THREAD

**Issue by Renpona** [notasuka/Viberaria#6]
Neither Damage Vibration nor Effect Damage Vibration are working for me.

There seems to be no extra effect from taking hits or taking lava damage when these two settings are on. If I turn off Health Vibration and leave just these two settings on, then regardless of what happens in game, the vibration level stays at whatever it was before.

Game environment:
Viberaria 2.9, with no other mods
tModLoader v2024.3.3.2
Terraria v1.4.4.9

**Comment by MysticMia** [comment]
This is likely caused by the bug referenced in #9 because it passes `Player.IsDead` instead of `!Player.IsDead` to the `public static async void Damaged(Player.HurtInfo hurtInfo, bool alive, int maxHp)` function. Since the Damaged function assumes the given parameter is `alive`, it inverts the if statement and basically only checks if a player got hurt when they are dead (which is kinda silly).
